sudo: false
language: java
jdk:
  - openjdk8
  - oraclejdk8
before_install:
  - chmod +x gradlew
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d9b035ff1e40ae63598b
    on_success: change
    on_failure: always
    on_start: false
