# ===================================================================
# LAWENA APPLICATION CONFIGURATION
#
# Can be overriden using Spring profiles, for instance:
#   file "application-dev.yml" if using --spring.profiles.active=dev
# Files should be placed in the Lawena root directory
# ===================================================================

# -------------------------------------------------------------------
# The following configures default profile/launcher values,
# Similar to the hard-coded values but with a functional Launcher
# -------------------------------------------------------------------
lawena:
  selected: Default
  profiles:
    - name: Default
      launcher: Team Fortress 2
  launchers:
    -
      name: Team Fortress 2
      icon: /com/github/lawena/views/tf2/tf2-red-48px.png
      launchMode: HL2
      modName: tf
      appId: '440'
      gameExecutable:
        windows: hl2.exe
        linux: hl2.sh
        osx: hl2.sh
      gameProcess:
        windows: hl2.exe
        linux: hl2_linux
        osx: hl2_osx
      gamePath: ''
      basePath: tf2
      viewName: tf2
      flags:
        - key: tf2.cfg.motionBlur
          defaultValue: true
          trueMappedValue: 1
          falseMappedValue: 0
        - key: tf2.cfg.noDamageNumbers
          defaultValue: true
          trueMappedValue: 0
          falseMappedValue: 1
        - key: tf2.cfg.noCrosshairSwitch
          defaultValue: false
          trueMappedValue: '//'
          falseMappedValue: false
        - key: tf2.cfg.noHitsounds
          defaultValue: true
          trueMappedValue: 0
          falseMappedValue: 1
        - key: tf2.cfg.noVoice
          defaultValue: true
          trueMappedValue: 0
          falseMappedValue: 1
        - key: tf2.cfg.hudMinmode
          defaultValue: false
          trueMappedValue: 1
          falseMappedValue: 0
        - key: tf2.cfg.hudPlayerModel
          defaultValue: false
          trueMappedValue: 1
          falseMappedValue: 0
        - key: tf2.cfg.noCrosshair
          defaultValue: false
          trueMappedValue: 0
          falseMappedValue: 1
      settings:
        host_timescale: 0.001
        volume: 0.5
        key_record: P
        key_toggleragdolls: R
        key_lockviewmodelsoff: F1
        key_lockviewmodelson: F2
        key_lockviewmodels: N
        key_lockcrosshair: M
        key_fpsup: UPARROW
        key_fpsdown: DOWNARROW
        key_showhelp: F3
        key_togglehud: H
        key_togglenotices: K
        key_cam_back: KP_DOWNARROW
        key_cam_backleft: KP_END
        key_cam_left: KP_LEFTARROW
        key_cam_frontleft: KP_HOME
        key_cam_front: KP_UPARROW
        key_cam_frontright: KP_PGUP
        key_cam_right: KP_RIGHTARROW
        key_cam_backright: KP_PGDN
        key_toggledist: KP_5
        key_togglepitch: KP_INS
        key_firstperson: KP_MINUS
        key_thirdperson: KP_PLUS
logging:
  file: logs/lawena.log.txt
  level:
    com.github.lawena:
      domain.AppProfile: INFO
      service.util:
        CopyDirVisitor: INFO
        DeleteDirVisitor: INFO
    java.util.prefs: ERROR
spring:
  jmx:
    enabled: false
