# ===================================================================
# LAWENA APPLICATION CONFIGURATION
#
# Can be overriden using Spring profiles, for instance:
#   file "application-dev.yml" if using --spring.profiles.active=dev
# Files should be placed in the Lawena root directory
# ===================================================================

# -------------------------------------------------------------------
# The following configures default profile/launcher values,
# Similar to the hard-coded values but with a functional Launcher
# -------------------------------------------------------------------
lawena:
  selected: Default
  profiles:
    - name: Default
      launcher: Team Fortress 2
  launchers:
    -
      name: Team Fortress 2
      icon: /com/github/lawena/views/tf2/tf2-red-48px.png
      launchMode: HL2
      modName: tf
      appId: '440'
      gameExecutable:
        windows: hl2.exe
        linux: hl2.sh
        osx: hl2.sh
      gameProcess:
        windows: hl2.exe
        linux: hl2_linux
        osx: hl2_osx
      gamePath: ''
      basePath: tf2
      viewName: tf2
      flags:
        - key: tf2.cfg.motionBlur
          defaultValue: true
          trueMappedValue: 1
          falseMappedValue: 0
        - key: tf2.cfg.noDamageNumbers
          defaultValue: true
          trueMappedValue: 0
          falseMappedValue: 1
        - key: tf2.cfg.noCrosshairSwitch
          defaultValue: false
          trueMappedValue: '//'
          falseMappedValue: false
        - key: tf2.cfg.noHitsounds
          defaultValue: true
          trueMappedValue: 0
          falseMappedValue: 1
        - key: tf2.cfg.noVoice
          defaultValue: true
          trueMappedValue: 0
          falseMappedValue: 1
        - key: tf2.cfg.hudMinmode
          defaultValue: false
          trueMappedValue: 1
          falseMappedValue: 0
        - key: tf2.cfg.hudPlayerModel
          defaultValue: false
          trueMappedValue: 1
          falseMappedValue: 0
        - key: tf2.cfg.noCrosshair
          defaultValue: false
          trueMappedValue: 0
          falseMappedValue: 1
      settings:
        host_timescale: 0.001
        volume: 0.5
        key.record: P
        key.toggleragdolls: R
        key.lockviewmodelsoff: F1
        key.lockviewmodelson: F2
        key.lockviewmodels: N
        key.lockcrosshair: M
        key.fpsup: UPARROW
        key.fpsdown: DOWNARROW
        key.showhelp: F3
        key.togglehud: H
        key.togglenotices: K
        key.cam.back: KP_DOWNARROW
        key.cam.backleft: KP_END
        key.cam.left: KP_LEFTARROW
        key.cam.frontleft: KP_HOME
        key.cam.front: KP_UPARROW
        key.cam.frontright: KP_PGUP
        key.cam.right: KP_RIGHTARROW
        key.cam.backright: KP_PGDN
        key.toggledist: KP_5
        key.togglepitch: KP_INS
        key.firstperson: KP_MINUS
        key.thirdperson: KP_PLUS
logging:
  file: logs/lawena.log.txt
  level:
    com.github.lawena:
      domain.AppProfile: INFO
      service.util:
        CopyDirVisitor: INFO
        DeleteDirVisitor: INFO
    java.util.prefs: ERROR
spring:
  jmx:
    enabled: false
